[bootstrapper] [ERROR] Command failed: npm run test
C:\Users\funey\repos\rhea\node_modules\better-sqlite3\lib\database.js:32
		throw new TypeError('Cannot open database because the directory does not exist');
		^

TypeError: Cannot open database because the directory does not exist
    at new Database (C:\Users\funey\repos\rhea\node_modules\better-sqlite3\lib\database.js:32:9)
    at new module.exports (C:\Users\funey\repos\rhea\db\sqlite.js:9:16)
    at Client.<anonymous> (C:\Users\funey\repos\rhea\index.js:77:17)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (C:\Users\funey\repos\rhea\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\funey\repos\rhea\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\funey\repos\rhea\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\funey\repos\rhea\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\funey\repos\rhea\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\funey\repos\rhea\node_modules\ws\lib\event-target.js:125:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rhea@0.0.3 test: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rhea@0.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\funey\AppData\Roaming\npm-cache\_logs\2020-10-14T17_25_35_836Z-debug.log
